### ISSUE TITLE
html: xmp repeatedly shows up

### ISSUE THREAD

**Issue by paulozoom** [sydlawrence/alfred-dev-doctor#11]
When using the HTML documentation, multiple results for xmp show up.

![Screen Shot 2013-03-25 at 6 01 49 PM](https://f.cloud.github.com/assets/69427/299001/cb43dfe8-956d-11e2-902d-488fd5af7bb1.png)

![Screen Shot 2013-03-25 at 6 02 11 PM](https://f.cloud.github.com/assets/69427/299005/d73e4888-956d-11e2-92ff-9558f33b0c73.png)

**Comment by cfeduke** [comment]
I noticed this too when I was working with the Clojure data. When I searched for a namespace term, like "core", I may get 9 results where all of them were the same exact value. Then if I clear and search for a function name, like "lefts" I will get 1 result of "lefts" and then 8 more results that were previously returned by the incorrect "core" search  (for a total of 9 results).

**Comment by sydlawrence** [comment]
Thanks guys, yeah this has been fixed in the latest build, thanks for pointing it out :)
