### ISSUE TITLE
Can't install as a Workflow?

### ISSUE THREAD

**Issue by Integralist** [sydlawrence/alfred-dev-doctor#16]
I'm using version 1.3.3 (267) on Mac OS X 10.8.3 - and yes I have Powerpack installed.

I try to drag and drop the downloaded file (`Dev Doctor.alfredworkflow`) but it wont allow me to.

Not sure where to start on how to debug or install?

Thanks.

**Comment by cfeduke** [comment]
These new workflows require Alfred 2.0. (It is not a free upgrade for Alfred 1.0 users, but there is a discount during the check out process, and they offer a perpetual upgrade license now as well.)

**Comment by sydlawrence** [comment]
Yup, what cfeduke said
