### ISSUE TITLE
Support for Coffeescript

### ISSUE THREAD

**Issue by lmartins** [sydlawrence/alfred-dev-doctor#2]
Thanks for the excellent workflow.
Would love if support for Coffeescript could be added.

**Comment by sydlawrence** [comment]
My understanding is that coffesscript uses the same function names as javascript, so how do you see this working for coffeescript?

**Comment by xumx** [comment]
yeah. exactly. coffee script is just syntax sugar. I don't think there is any documentation.

**Comment by lmartins** [comment]
Coffeescript has different syntax and dedicated docs: http://coffeescript.org/
It just a convenience, but that's the goal of this workflow anyway.

**Comment by sydlawrence** [comment]
if you would like to add a coffeescript parser, go ahead :) as you can see from the others, it's pretty straight froward :)

**Comment by theinterned** [comment]
Why is this closed? It doesn't seem like coffeescript has been added?
