### ISSUE TITLE
Better JavaScript support

### ISSUE THREAD

**Issue by dv8godd** [sydlawrence/alfred-dev-doctor#24]
It would be nice if there were better javascript support.  As it stands, the js docs seem to be missing a lot.  For instance, searching for anything related to DOM seems missing like "getElementById" or "className" etc.  Unless I'm missing something?

**Comment by sydlawrence** [comment]
Yeah, I have noticed that, I am not 100% sure where to get the best data from

**Comment by dv8godd** [comment]
I think you can keep using MDN, honestly.  Data pertaining to the DOM is available there readily, it just doesn't show up in search results as "JavaScript", it shows up as "Document Object Model (DOM)" or just "DOM".  For some reason, MDN seems to classify DOM more under HTML than JavaScript in their "Docs" navigation.

**Comment by sydlawrence** [comment]
perfect response thanks @dv8godd, with that knowledge I have now added the DOM parts into the js parser.

This has vastly improved it.

Thanks :)
