### ISSUE TITLE
Add support for Alleyoop

### ISSUE THREAD

**Issue by bryanforbes** [sydlawrence/alfred-dev-doctor#27]
This is a great workflow, but I noticed that it has had a few updates since I first installed it. It would be nice if you could add support for the Alleyoop workflow which allows updating a workflow when new releases come out. For more information, check out http://www.alfredforum.com/topic/1582-alleyoop-update-alfred-workflows/.

**Comment by sydlawrence** [comment]
The latest version on github auto updates

**Comment by bryanforbes** [comment]
Very nice. You can ignore this feature request!
