### ISSUE TITLE
search for npm modules

### ISSUE THREAD

**Issue by wilmoore** [sydlawrence/alfred-dev-doctor#38]
![](http://i.cloudup.com/1BUhJ1kodD.png)
## Search Dialog

![](http://i.cloudup.com/o2Wlbj82gy.png)
## Keyword Setup

![](http://i.cloudup.com/5AaSDhBsbY.png)
## Open Url

![](http://i.cloudup.com/EH0HiZv4zK.png)
## End Result

![](http://i.cloudup.com/pe5ziy6Ax6.png)
## Icon

```
http://i.cloudup.com/1BUhJ1kodD.png
```

**Comment by mbrevoort** [comment]
@wilmoore Just stumbled upon this :) This would be more awesome if it searched http://npmsearch.com/?q= instead!

**Comment by wilmoore** [comment]
> would be more awesome if it searched http://npmsearch.com/?q= instead!

Agreed. done. :+1:

**Comment by willfarrell** [comment]
Check out https://github.com/willfarrell/alfred-pkgman-workflow
npm is included

**Comment by wilmoore** [comment]
_edited_ 

I've also recently found https://github.com/zenorocha/alfred-workflows. Seem like that one and the one by @willfarrell have a lot of overlap. Need to get these into one project; seriously. This is getting crazy.

OH; I see, looks like https://github.com/zenorocha/alfred-workflows uses https://github.com/willfarrell/alfred-pkgman-workflow for the package managers. Cool; as long as they are kept up-to-date.

**Comment by wilmoore** [comment]
BTW, since once could just choose either:
- https://github.com/willfarrell/alfred-pkgman-workflow
- https://github.com/zenorocha/alfred-workflows

I'll close this issue.

**Comment by willfarrell** [comment]
All my workflows have `oop` support for updating to the latest version.
