### ISSUE TITLE
Automatically update datasets

### ISSUE THREAD

**Issue by keithamus** [sydlawrence/alfred-dev-doctor#6]
When searching, the workflow should detect how stale datasets are. It seems at the moment you have to manually update when you feel the data is stale.
#### Proposal:

search.php checks the last-modified date of the file, and if older than, say, a week, runs `$parser->update();`

**Comment by sydlawrence** [comment]
Yeah, that could definitely work, nice thinking keith.

I've been asked to write a guide about creating your own parsers, so I am gonna do that and the README tonight :)
