### ISSUE TITLE
Python fragment identifiers broken

### ISSUE THREAD

**Issue by protocol7** [sydlawrence/alfred-dev-doctor#7]
Some of the Python fragment identifiers are broken, e.g.:
py string.join => 
http://docs.python.org/2/library/string.html#string_string.join
should be:
http://docs.python.org/2/library/string.html#string.join

py dict.clear =>
http://docs.python.org/2/library/stdtypes.html#_dict.clear
should be:
http://docs.python.org/2/library/stdtypes.html#dict.clear

I'm not sure what the appropriate fix is, or I have tried to fix it myself.

Thanks for an excellent workflow!

/niklas

**Comment by sydlawrence** [comment]
Thanks :) i'll take a look at it

**Comment by sydlawrence** [comment]
This is now fixed in the latest version, thanks for pointing it out :)

**Comment by protocol7** [comment]
Impressive speed :) Thanks!

**Comment by sydlawrence** [comment]
no problem :) thanks for reporting it
